# Generated by Django 4.2.17 on 2025-01-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadministrador', '0003_remove_usuario_state_usuario_id_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='nombre',
            new_name='name',
        ),
    ]
