# Generated by Django 4.2.17 on 2025-01-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadministrador', '0004_rename_nombre_rol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_rol', to='appadministrador.rol'),
        ),
    ]
