# Generated by Django 4.2.17 on 2025-01-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadministrador', '0005_alter_usuario_id_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='id_tipo_votacion',
            new_name='id_tipovotacion',
        ),
        migrations.AlterField(
            model_name='plancha',
            name='id_tipovotacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TipoVotacion', to='appadministrador.tipovotacion'),
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('usuario', 'id_plancha', 'id_tipovotacion')},
        ),
    ]
