# Generated by Django 4.2.17 on 2025-01-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadministrador', '0006_rename_id_tipo_votacion_voto_id_tipovotacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plancha',
            old_name='id_tipovotacion',
            new_name='tipovotacion',
        ),
    ]
