# Generated by Django 4.2.17 on 2025-01-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadministrador', '0007_rename_id_tipovotacion_plancha_tipovotacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancha',
            name='tipovotacion',
        ),
        migrations.AddField(
            model_name='plancha',
            name='id_tipovotacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_tipovotacion', to='appadministrador.tipovotacion'),
        ),
    ]
