# Generated by Django 4.2.17 on 2025-01-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadministrador', '0008_remove_plancha_tipovotacion_plancha_id_tipovotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancha',
            name='id_tipovotacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_tipovotacion', to='appadministrador.tipovotacion'),
        ),
    ]
