# Generated by Django 4.2.17 on 2025-01-12 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appadministrador', '0011_rol_state_tipovotacion_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovotacion',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tipovotacion',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
